### ISSUE TITLE
Player View Bug Fix

### ISSUE THREAD

**Issue by portalsam1** [Ashleyz4/MC_b1.7.3-MegaMod#3] opened 2019-04-30 01:21 UTC
Could you look into the bug that snaps your view to the floor when you exit a chest/chat?

**Comment by ScarletLovell** [comment] 2019-04-30 18:51
This one actually doesn't happen for me. Can you tell me how to reproduce?

**Comment by portalsam1** [comment] 2019-04-30 20:43
The bug is very situational and doesn't seem to occur anymore. I used to be able to just say something in chat or close a chest and it would happen 90% of the time. Strange.

**Comment by ScarletLovell** [comment] 2019-04-30 23:15
Closing for now since it can't be replicated

**Closed as completed by ScarletLovell** 2019-04-30 23:15 UTC
Labels: bug, Idea
